import numpy as np
import matplotlib.pyplot as plt
phi=np.linspace(0, np.pi, 100)
theta=(np.arange(0,2*np.pi,0.01))
r1 = 1*(abs(np.sin(theta)))*((abs(np.cos(theta)))**0.5)
r2 = 2*(abs(np.sin(theta)))*((abs(np.cos(theta)))**0.5)
r3 = 3*(abs(np.sin(theta)))*((abs(np.cos(theta)))**0.5)
r4 = 4*(abs(np.sin(theta)))*((abs(np.cos(theta)))**0.5)
r5 = 5*(abs(np.sin(theta)))*((abs(np.cos(theta)))**0.5)

a1 = plt.subplot(111, polar=True)
a1.plot(theta,r1, color='r', linewidth=3)
a1.set_rmax(5.0)
a1.grid(True)
a2 = plt.subplot(111, polar=True)
a2.plot(theta,r2, color='g', linewidth=3)
a2.set_rmax(5.0)
a2.grid(True)
a3 = plt.subplot(111, polar=True)
a3.plot(theta,r3, color='b', linewidth=3)
a3.set_rmax(5.0)
a3.grid(True)
a4 = plt.subplot(111, polar=True)
a4.plot(theta,r4, color='black', linewidth=3)
a4.set_rmax(5.0)
a4.grid(True)
a5 = plt.subplot(111, polar=True)
a5.plot(theta,r5, color='m', linewidth=3)
a5.set_rmax(5.0)
a5.grid(True)
plt.show()